# Generated by Django 4.1.4 on 2022-12-19 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departname', models.CharField(max_length=16, unique=True, verbose_name='部门名称')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=16, verbose_name='IP地址')),
                ('mac_addr', models.CharField(max_length=14, verbose_name='MAC地址')),
                ('interface', models.CharField(max_length=16, verbose_name='接口')),
                ('cap_datetime', models.DateTimeField(verbose_name='采集时间')),
            ],
            options={
                'verbose_name': 'ARP表',
                'ordering': ['cap_datetime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名称')),
                ('status', models.SmallIntegerField(choices=[(None, '请选择'), (0, '正常'), (1, '失效')], default=None, null=True, verbose_name='状态')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department', verbose_name='所在部门')),
            ],
            options={
                'verbose_name': '人员基本信息',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.SmallIntegerField(choices=[(0, '联想'), (1, '惠普')], default=0, verbose_name='品牌')),
                ('computer_type', models.CharField(max_length=16, null=True, verbose_name='型号')),
                ('serial_number', models.CharField(max_length=32, unique=True, verbose_name='序列号')),
                ('production_date', models.DateField(default=django.utils.timezone.now, verbose_name='生产日期')),
                ('mac_addr', models.CharField(default=None, max_length=14, verbose_name='MAC地址')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('img', models.FileField(null=True, upload_to='computer/', verbose_name='图片')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='app1.user', verbose_name='拥有者')),
            ],
        ),
    ]
