# Generated by Django 4.1.4 on 2022-12-13 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departname', models.CharField(max_length=16, verbose_name='部门名称')),
                ('createdate', models.DateTimeField(verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名称')),
                ('status', models.CharField(max_length=1, verbose_name='状态')),
                ('createdate', models.DateTimeField(verbose_name='创建日期')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.department')),
            ],
            options={
                'verbose_name': '人员基本信息',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=16)),
                ('computer_type', models.CharField(max_length=16)),
                ('serial_number', models.CharField(max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.user')),
            ],
        ),
    ]
