# Generated by Django 4.1.4 on 2022-12-14 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departname', models.CharField(max_length=16, unique=True, verbose_name='部门名称')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名称')),
                ('status', models.SmallIntegerField(choices=[(None, '请选择'), (0, '正常'), (1, '失效')], default=None, verbose_name='状态')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department', verbose_name='所在部门')),
            ],
            options={
                'verbose_name': '人员基本信息',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.SmallIntegerField(choices=[(0, '联想'), (1, '惠普')], verbose_name='品牌')),
                ('computer_type', models.CharField(max_length=16, verbose_name='型号')),
                ('serial_number', models.CharField(max_length=32, unique=True, verbose_name='序列号')),
                ('mac_addr', models.CharField(default=None, max_length=14)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user', verbose_name='拥有者')),
            ],
        ),
    ]
