# Generated by Django 4.1.4 on 2022-12-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='brand',
            field=models.CharField(max_length=16, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(max_length=16, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.user', verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(max_length=32, verbose_name='序列号'),
        ),
    ]
