# Generated by Django 4.1.4 on 2022-12-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': '电脑', 'verbose_name_plural': '电脑'},
        ),
        migrations.AlterModelOptions(
            name='ipaddr',
            options={'ordering': ['cap_datetime'], 'verbose_name': 'ARP表', 'verbose_name_plural': 'ARP表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '人员基本信息', 'verbose_name_plural': '人员基本信息'},
        ),
        migrations.AlterField(
            model_name='computer',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='computer/', verbose_name='图片'),
        ),
    ]
