# Generated by Django 4.1.4 on 2022-12-14 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生产日期'),
        ),
    ]
