# Generated by Django 4.1.4 on 2022-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_computer_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='mac_addr',
            field=models.CharField(default=None, max_length=14, verbose_name='MAC地址'),
        ),
    ]
