# Generated by Django 4.1.4 on 2022-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_computer_mac_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
