# Generated by Django 4.1.4 on 2022-12-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_computer_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
