# Generated by Django 4.1.4 on 2022-12-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='department',
            name='departname',
            field=models.CharField(max_length=16, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.department', verbose_name='所在部门'),
        ),
    ]
