# Generated by Django 4.1.4 on 2022-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='状态'),
        ),
    ]
