# Generated by Django 4.1.4 on 2022-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[(None, '请选择'), (0, '正常'), (1, '失效')], default='', max_length=1, null=True, verbose_name='状态'),
        ),
    ]
