# Generated by Django 4.1.4 on 2022-12-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_computer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='img',
            field=models.FileField(null=True, upload_to='computer/', verbose_name='图片'),
        ),
    ]
