# Generated by Django 4.1.4 on 2022-12-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department', verbose_name='所在部门'),
        ),
    ]
