# Generated by Django 4.1.4 on 2022-12-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_ipaddr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddr',
            options={'ordering': ['cap_datetime']},
        ),
    ]
